deltaruneTargetVersion = "1.04"

[metadata]
name = "Custom Difficulty"
version = "1.8.6"
description = "Difficulty options for DELTARUNE. Make the game Easy, Hard, or Nightmare. No-hit options included."
author = [ "Emmahaha" ]
packageID = "com.emmahaha.customdiffdemo"
game = "toby.deltarune.demo"
url = "https://gamebanana.com/mods/613308"
mergeSupport = true
tags = [ "customization", "gameplay" ]

[color]
r = 255
g = 0
b = 0

[[neededFiles]]
file = "./data.win"
checksum = "4de4118ba4ad4243025e61337fe796532751032c0a04d0843d8b35f91ec2c220"