deltaruneTargetVersion = "1.04"

[metadata]
name = "ModMenu"
version = "2.0.2"
description = "ModMenu for DELTARUNE. Framework for mods to add settings menus."
author = [ "Emmahaha" ]
packageID = "com.emmahaha.modmenudemo"
game = "toby.deltarune.demo"
url = "https://gamebanana.com/tools/20839"
mergeSupport = true
tags = [ "other" ]

[color]
r = 255
g = 0
b = 0

[[neededFiles]]
file = "./data.win"
checksum = "4de4118ba4ad4243025e61337fe796532751032c0a04d0843d8b35f91ec2c220"